'use client'

import { useState, useCallback, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import type { CountryData } from '@/types/country'
import type { InvestmentReport, SectorOutlook } from '@/app/api/report/[countryCode]/route'

// ── Recommendation colour system ──────────────────────────────────────────────
function recStyle(rec: InvestmentReport['overallRecommendation']) {
  switch (rec) {
    case 'STRONG BUY': return { color: '#00ff8c', bg: 'rgba(0,255,140,0.08)', border: 'rgba(0,255,140,0.25)', label: 'STRONG BUY' }
    case 'BUY':        return { color: '#22c55e', bg: 'rgba(34,197,94,0.08)', border: 'rgba(34,197,94,0.22)', label: 'BUY' }
    case 'HOLD':       return { color: '#FFD166', bg: 'rgba(255,209,102,0.07)', border: 'rgba(255,209,102,0.20)', label: 'HOLD' }
    case 'UNDERWEIGHT':return { color: '#fb923c', bg: 'rgba(251,146,60,0.08)', border: 'rgba(251,146,60,0.22)', label: 'UNDERWEIGHT' }
    case 'AVOID':      return { color: '#ef4444', bg: 'rgba(239,68,68,0.08)', border: 'rgba(239,68,68,0.22)', label: 'AVOID' }
  }
}

function signalDot(signal: SectorOutlook['signal']) {
  return signal === 'positive' ? '#22c55e' : signal === 'negative' ? '#ef4444' : '#FFD166'
}

// ── Print-to-PDF: opens a new window with report HTML ───────────────────────
function downloadPDF(report: InvestmentReport, flag: string) {
  const rec = recStyle(report.overallRecommendation)
  const now = new Date(report.generatedAt).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  })

  const strengthsHtml = report.economicStrengths.map(s =>
    `<li>${s}</li>`
  ).join('')
  const risksHtml = report.economicRisks.map(r =>
    `<li>${r}</li>`
  ).join('')
  const oppsHtml = report.investmentOpportunities.map(o =>
    `<li>${o}</li>`
  ).join('')
  const sectorsHtml = report.keySectors.map(s => {
    const color = s.signal === 'positive' ? '#22c55e' : s.signal === 'negative' ? '#ef4444' : '#f59e0b'
    return `<tr><td style="font-weight:600;padding:6px 12px 6px 0">${s.name}</td><td style="color:${color};padding:6px 12px 6px 0;text-transform:uppercase;font-size:11px;font-weight:700">${s.signal}</td><td style="padding:6px 0;color:#555;font-size:13px">${s.outlook}</td></tr>`
  }).join('')

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>PulseEarth — ${report.country} Investment Report</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Georgia', serif; color: #1a1a2e; background: #fff; padding: 60px 72px; max-width: 900px; margin: 0 auto; }
  .header { border-bottom: 3px solid #1a1a2e; padding-bottom: 20px; margin-bottom: 32px; }
  .brand { font-size: 11px; letter-spacing: 3px; text-transform: uppercase; color: #666; margin-bottom: 8px; }
  .title { font-size: 28px; font-weight: 700; margin-bottom: 6px; }
  .subtitle { font-size: 13px; color: #555; }
  .rec-badge { display: inline-block; padding: 6px 20px; border-radius: 4px; font-weight: 800; font-size: 14px; letter-spacing: 2px; margin-top: 14px; background: ${rec.bg}; border: 1.5px solid ${rec.border}; color: ${rec.color}; }
  h2 { font-size: 11px; letter-spacing: 2.5px; text-transform: uppercase; color: #888; border-bottom: 1px solid #e5e5e5; padding-bottom: 6px; margin: 28px 0 14px; }
  p { font-size: 14px; line-height: 1.75; color: #2a2a3e; }
  ul { margin: 0; padding-left: 20px; }
  ul li { font-size: 13.5px; line-height: 1.65; color: #2a2a3e; margin-bottom: 5px; }
  table { width: 100%; border-collapse: collapse; }
  .footer { margin-top: 48px; padding-top: 20px; border-top: 1px solid #e5e5e5; font-size: 10px; color: #aaa; line-height: 1.5; }
  .confidence { display: inline-block; font-size: 12px; color: #888; margin-left: 12px; }
  @media print {
    body { padding: 20px 40px; }
    @page { margin: 20mm; }
  }
</style>
</head>
<body>
<div class="header">
  <div class="brand">PulseEarth · Economic Intelligence</div>
  <div class="title">${flag} ${report.country}</div>
  <div class="subtitle">Investment Research Report · Generated ${now} · Data: World Bank / IMF ${report.dataYear}</div>
  <div class="rec-badge">${rec.label}</div>
  <span class="confidence">Confidence ${report.confidenceScore}/10</span>
</div>

<h2>Executive Summary</h2>
<p>${report.executiveSummary}</p>

<h2>Economic Strengths</h2>
<ul>${strengthsHtml}</ul>

<h2>Economic Risks</h2>
<ul>${risksHtml}</ul>

<h2>Trade Analysis</h2>
<p>${report.tradeAnalysis}</p>

<h2>Investment Opportunities</h2>
<ul>${oppsHtml}</ul>

<h2>Key Sectors</h2>
<table>${sectorsHtml}</table>

<h2>Growth Outlook (12–18 months)</h2>
<p>${report.growthOutlook}</p>

<h2>Recommendation Rationale</h2>
<p>${report.recommendationRationale}</p>

<div class="footer">
  This report was generated by PulseEarth AI using verified macroeconomic data from the World Bank, IMF, and live market news.
  All figures are sourced from the most recent available period. This document is for informational purposes only and does not constitute financial advice.
  PulseEarth Economic Intelligence · pulseearth.ai · ${now}
</div>
</body>
</html>`

  const w = window.open('', '_blank', 'width=900,height=700')
  if (!w) return
  w.document.write(html)
  w.document.close()
  w.focus()
  setTimeout(() => { w.print() }, 600)
}

// ── Loading skeleton ──────────────────────────────────────────────────────────
function Skeleton() {
  return (
    <div className="space-y-5 animate-pulse">
      {[80, 48, 64, 48, 56, 40, 56].map((h, i) => (
        <div key={i} className="rounded-lg bg-white/[0.03]" style={{ height: h }} />
      ))}
    </div>
  )
}

// ── Props ─────────────────────────────────────────────────────────────────────
interface Props {
  countryCode: string
  countryName: string
  countryData: CountryData | null
  flag?: string
}

// ── Main component ────────────────────────────────────────────────────────────
export default function InvestmentReport({ countryCode, countryName, countryData, flag = '' }: Props) {
  const [isOpen,   setIsOpen]   = useState(false)
  const [loading,  setLoading]  = useState(false)
  const [report,   setReport]   = useState<InvestmentReport | null>(null)
  const [error,    setError]    = useState(false)

  // Reset when country changes
  useEffect(() => { setIsOpen(false); setReport(null); setError(false) }, [countryCode])

  const generateReport = useCallback(async () => {
    if (report) { setIsOpen(true); return }
    setIsOpen(true)
    setLoading(true)
    setError(false)

    // Fetch news in parallel for richer report
    let articles: string[] = []
    try {
      const nRes = await fetch(`/api/news/${encodeURIComponent(countryCode)}`)
      if (nRes.ok) {
        const d = await nRes.json()
        articles = (d.articles ?? []).slice(0, 5).map((a: { title: string }) => a.title)
      }
    } catch { /* continue without news */ }

    try {
      const d = countryData
      const res = await fetch(`/api/report/${encodeURIComponent(countryCode)}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          countryName,
          countryCode,
          articles,
          capital:         d?.capital       ?? null,
          region:          d?.region        ?? null,
          gdp:             d?.gdp_billion   ?? null,
          gdpGrowth:       d?.gdpGrowth     ?? null,
          population:      d?.population_m  ?? null,
          inflation:       d?.inflation     ?? null,
          unemployment:    d?.unemployment  ?? null,
          gdpPerCapita:    d?.gdpPerCapita  ?? null,
          riskScore:       d?.risk_score    ?? null,
          innovationScore: d?.innovationScore ?? null,
        }),
      })
      if (!res.ok) throw new Error('error')
      setReport(await res.json())
    } catch {
      setError(true)
    } finally {
      setLoading(false)
    }
  }, [countryCode, countryName, countryData, report])

  const rec = report ? recStyle(report.overallRecommendation) : null

  return (
    <>
      {/* Trigger button */}
      <motion.button
        initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.28 }}
        onClick={generateReport}
        className="w-full flex items-center gap-3 px-4 py-3 rounded-xl border transition-all group"
        style={{
          borderColor: 'rgba(255,209,102,0.22)',
          background: 'rgba(255,209,102,0.04)',
        }}
      >
        <span className="text-base flex-shrink-0">📄</span>
        <div className="flex-1 text-left min-w-0">
          <p className="text-[12px] font-semibold text-[#FFD166]/80 group-hover:text-[#FFD166] transition-colors">
            Generate Investment Report
          </p>
          <p className="text-[9px] text-white/22 mt-0.5">Goldman Sachs · McKinsey · Bloomberg style</p>
        </div>
        <span className="text-[10px] text-white/20 flex-shrink-0">PDF ↗</span>
      </motion.button>

      {/* Full-screen report modal */}
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.22 }}
            className="fixed inset-0 z-50 flex flex-col"
            style={{ background: 'rgba(4,8,18,0.98)' }}
          >
            {/* Modal header */}
            <div
              className="flex items-center justify-between px-8 py-4 flex-shrink-0"
              style={{ borderBottom: '1px solid rgba(255,209,102,0.12)' }}
            >
              <div className="flex items-center gap-4">
                <span className="text-[10px] text-[#FFD166]/40 uppercase tracking-[0.22em]">PulseEarth · Investment Research</span>
                {report && rec && (
                  <span
                    className="text-[10px] font-bold px-3 py-1 rounded-full tracking-widest"
                    style={{ color: rec.color, background: rec.bg, border: `1px solid ${rec.border}` }}
                  >
                    {rec.label}
                  </span>
                )}
                {report && (
                  <span className="text-[10px] text-white/25">
                    Confidence {report.confidenceScore}/10
                  </span>
                )}
              </div>
              <div className="flex items-center gap-3">
                {report && (
                  <button
                    onClick={() => downloadPDF(report, flag)}
                    className="flex items-center gap-2 px-4 py-1.5 rounded-lg text-[11px] font-semibold text-[#FFD166]/80 hover:text-[#FFD166] border border-[#FFD166]/20 hover:border-[#FFD166]/40 transition-all"
                  >
                    <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                      <path d="M6 1v7M3 5l3 3 3-3M1 10h10" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round" />
                    </svg>
                    Download PDF
                  </button>
                )}
                {!loading && (
                  <button
                    onClick={() => { setReport(null); generateReport() }}
                    className="text-[10px] text-white/25 hover:text-white/50 transition-colors uppercase tracking-wider"
                  >
                    ↺ Regenerate
                  </button>
                )}
                <button
                  onClick={() => setIsOpen(false)}
                  className="w-7 h-7 rounded-full flex items-center justify-center text-white/30 hover:text-white/70 hover:bg-white/08 transition-all text-lg leading-none"
                >
                  ×
                </button>
              </div>
            </div>

            {/* Scrollable report body */}
            <div className="flex-1 overflow-y-auto">
              <div className="max-w-3xl mx-auto px-8 py-8">

                {/* Country header */}
                <div className="mb-8">
                  <div className="flex items-center gap-3 mb-1">
                    {flag && <span className="text-3xl">{flag}</span>}
                    <div>
                      <h1 className="text-[28px] font-bold text-white leading-none">{countryName}</h1>
                      <p className="text-[11px] text-white/28 mt-1 tracking-wide">
                        Investment Research Report · Data: World Bank / IMF {report?.dataYear ?? '2023'} ·
                        Generated {report ? new Date(report.generatedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) : '…'}
                      </p>
                    </div>
                  </div>
                </div>

                {loading && <Skeleton />}
                {error && (
                  <div className="rounded-xl p-6 border border-red-500/20 bg-red-500/05">
                    <p className="text-white/50 text-sm">Report generation failed. Check your AI API keys and retry.</p>
                    <button onClick={() => { setReport(null); setError(false); generateReport() }}
                      className="mt-3 text-[11px] text-[#FFD166]/60 hover:text-[#FFD166] transition-colors">
                      ↺ Try again
                    </button>
                  </div>
                )}

                {report && !loading && (
                  <div className="space-y-8">

                    {/* Executive Summary */}
                    <Section title="Executive Summary">
                      <p className="text-[14px] text-white/75 leading-relaxed font-light">{report.executiveSummary}</p>
                    </Section>

                    {/* Strengths + Risks side by side */}
                    <div className="grid grid-cols-2 gap-6">
                      <Section title="Economic Strengths">
                        <ul className="space-y-2">
                          {report.economicStrengths.map((s, i) => (
                            <li key={i} className="flex items-start gap-2">
                              <span className="text-emerald-400/60 flex-shrink-0 mt-0.5 text-[11px]">▸</span>
                              <p className="text-[12px] text-white/62 leading-snug">{s}</p>
                            </li>
                          ))}
                        </ul>
                      </Section>

                      <Section title="Economic Risks">
                        <ul className="space-y-2">
                          {report.economicRisks.map((r, i) => (
                            <li key={i} className="flex items-start gap-2">
                              <span className="text-red-400/60 flex-shrink-0 mt-0.5 text-[11px]">▸</span>
                              <p className="text-[12px] text-white/62 leading-snug">{r}</p>
                            </li>
                          ))}
                        </ul>
                      </Section>
                    </div>

                    {/* Trade Analysis */}
                    {report.tradeAnalysis && (
                      <Section title="Trade Analysis">
                        <p className="text-[13px] text-white/62 leading-relaxed">{report.tradeAnalysis}</p>
                      </Section>
                    )}

                    {/* Investment Opportunities */}
                    <Section title="Investment Opportunities">
                      <div className="space-y-3">
                        {report.investmentOpportunities.map((o, i) => (
                          <motion.div
                            key={i}
                            initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }}
                            transition={{ delay: 0.05 * i }}
                            className="flex items-start gap-3 p-3 rounded-lg"
                            style={{ background: 'rgba(255,209,102,0.04)', border: '1px solid rgba(255,209,102,0.10)' }}
                          >
                            <span className="text-[#FFD166]/60 font-bold text-sm flex-shrink-0">{i + 1}</span>
                            <p className="text-[12.5px] text-white/65 leading-snug">{o}</p>
                          </motion.div>
                        ))}
                      </div>
                    </Section>

                    {/* Key Sectors */}
                    <Section title="Key Sectors">
                      <div className="space-y-2">
                        {report.keySectors.map((s, i) => (
                          <div key={i} className="flex items-center gap-3 py-2.5 border-b border-white/[0.05]">
                            <div
                              className="w-2 h-2 rounded-full flex-shrink-0"
                              style={{ background: signalDot(s.signal) }}
                            />
                            <span className="text-[12px] font-semibold text-white/70 w-32 flex-shrink-0">{s.name}</span>
                            <span
                              className="text-[9px] uppercase tracking-widest font-bold px-2 py-0.5 rounded flex-shrink-0"
                              style={{
                                color: signalDot(s.signal),
                                background: `${signalDot(s.signal)}15`,
                              }}
                            >
                              {s.signal}
                            </span>
                            <p className="text-[11.5px] text-white/45 leading-snug">{s.outlook}</p>
                          </div>
                        ))}
                      </div>
                    </Section>

                    {/* Growth Outlook */}
                    {report.growthOutlook && (
                      <Section title="Growth Outlook · 12–18 Months">
                        <p className="text-[13px] text-white/62 leading-relaxed">{report.growthOutlook}</p>
                      </Section>
                    )}

                    {/* Overall Recommendation — hero card */}
                    {rec && (
                      <div
                        className="rounded-xl p-6 border"
                        style={{ background: rec.bg, borderColor: rec.border }}
                      >
                        <div className="flex items-center justify-between mb-3">
                          <p className="text-[10px] text-white/30 uppercase tracking-[0.2em]">Overall Recommendation</p>
                          <span
                            className="text-[22px] font-black tracking-widest"
                            style={{ color: rec.color }}
                          >
                            {rec.label}
                          </span>
                        </div>
                        <p className="text-[13px] leading-relaxed" style={{ color: `${rec.color}cc` }}>
                          {report.recommendationRationale}
                        </p>
                      </div>
                    )}

                    {/* Data sources footer */}
                    <div className="pt-6 border-t border-white/[0.06]">
                      <p className="text-[9px] text-white/20 uppercase tracking-wider mb-2">Data Provenance</p>
                      <p className="text-[10.5px] text-white/28 leading-relaxed">
                        All macroeconomic indicators (GDP, GDP Growth, Inflation, Unemployment, Trade) are sourced from
                        World Bank Open Data and IMF World Economic Outlook ({report.dataYear}).
                        News intelligence sourced from Reuters, Bloomberg, BBC Business, and local economic publications.
                        Risk and Innovation scores are PulseEarth composite indices derived from World Bank governance and
                        technology indicators. This report is generated by AI and should not be construed as financial advice.
                      </p>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <div className="flex items-center gap-3 mb-3">
        <p className="text-[9.5px] text-white/30 uppercase tracking-[0.22em] font-medium">{title}</p>
        <div className="flex-1 h-px bg-white/[0.06]" />
      </div>
      {children}
    </div>
  )
}
